description: 'Get runner registration token for a self-hosted runner'
inputs:
  organization:
    description: 'Who to greet'
    required: true
    default: 'traveloka'
  repository:
    description: 'Who to greet'
    required: true
  GH_PAT_TOKEN:
    description: 'Personal Access Token'
    required: true
outputs:
  token:
    description: "self-hosted runner registration token"
    value: ${{ steps.token.outputs.token }}
runs:
  using: "composite"
  steps:
    - id: token
      run: "echo token=$(curl -L -X POST -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ inputs.GH_PAT_TOKEN }}' -H 'X-GitHub-Api-Version: 2022-11-28' https://api.github.com/repos/${{ inputs.organization }}/${{ inputs.repository }}/actions/runners/registration-token | jq -r '.token') > $GITHUB_OUTPUT"
      shell: bash
